"use client";

import { useState } from "react";
import {
  DocumentDownload,
  TickCircle,
  Document,
  DocumentText1,
  Chart,
  Cpu,
} from "iconsax-react";
import { DialogTrigger as AriaDialogTrigger, Heading as AriaHeading } from "react-aria-components";
import { Dialog, Modal, ModalOverlay } from "@/components/application/modals/modal";
import { Button } from "@/components/base/buttons/button";
import { CloseButton } from "@/components/base/buttons/close-button";
import { Checkbox } from "@/components/base/checkbox/checkbox";
import { cx } from "@/utils/cx";

type ExportType = "document" | "report" | "ai-system";

interface ExportOption {
  id: string;
  label: string;
  description: string;
  checked: boolean;
}

interface PdfExportModalProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  exportType: ExportType;
  itemName: string;
  onExport?: (options: string[]) => void;
}

const exportTypeConfig = {
  document: {
    title: "Export Document",
    icon: DocumentText1,
    options: [
      { id: "content", label: "Document Content", description: "The full document text and formatting", checked: true },
      { id: "metadata", label: "Metadata", description: "Creation date, author, version history", checked: true },
      { id: "linked-requirements", label: "Linked Requirements", description: "Requirements this document satisfies", checked: false },
      { id: "watermark", label: "Add Watermark", description: "Include 'Generated by ComplyAI' watermark", checked: true },
    ],
  },
  report: {
    title: "Export Report",
    icon: Chart,
    options: [
      { id: "executive-summary", label: "Executive Summary", description: "High-level compliance overview", checked: true },
      { id: "ai-systems", label: "AI Systems Details", description: "All tracked AI systems and their status", checked: true },
      { id: "requirements", label: "Requirements Status", description: "Complete requirements breakdown", checked: true },
      { id: "documents", label: "Document Inventory", description: "List of all compliance documents", checked: true },
      { id: "evidence", label: "Evidence Summary", description: "Uploaded evidence files", checked: false },
      { id: "audit-trail", label: "Audit Trail", description: "Activity log and changes", checked: false },
    ],
  },
  "ai-system": {
    title: "Export AI System",
    icon: Cpu,
    options: [
      { id: "overview", label: "System Overview", description: "Basic information and classification", checked: true },
      { id: "requirements", label: "Requirements Checklist", description: "All requirements and their status", checked: true },
      { id: "documents", label: "Linked Documents", description: "Documents associated with this system", checked: true },
      { id: "evidence", label: "Evidence Files", description: "Uploaded evidence for requirements", checked: false },
      { id: "activity", label: "Activity History", description: "Recent changes and updates", checked: false },
    ],
  },
};

export const PdfExportModal = ({
  isOpen,
  onOpenChange,
  exportType,
  itemName,
  onExport,
}: PdfExportModalProps) => {
  const config = exportTypeConfig[exportType];
  const [options, setOptions] = useState<ExportOption[]>(
    config.options.map((opt) => ({ ...opt }))
  );
  const [isExporting, setIsExporting] = useState(false);
  const [isComplete, setIsComplete] = useState(false);

  const handleClose = () => {
    setIsExporting(false);
    setIsComplete(false);
    setOptions(config.options.map((opt) => ({ ...opt })));
    onOpenChange(false);
  };

  const toggleOption = (id: string) => {
    setOptions((prev) =>
      prev.map((opt) =>
        opt.id === id ? { ...opt, checked: !opt.checked } : opt
      )
    );
  };

  const handleExport = () => {
    setIsExporting(true);
    
    // Simulate PDF generation
    setTimeout(() => {
      setIsExporting(false);
      setIsComplete(true);
      
      const selectedOptions = options.filter((opt) => opt.checked).map((opt) => opt.id);
      onExport?.(selectedOptions);
    }, 2000);
  };

  const handleDownload = () => {
    // In production, this would trigger the actual download
    // For now, we'll simulate it
    const link = document.createElement("a");
    link.href = "#";
    link.download = `${itemName.toLowerCase().replace(/\s+/g, "-")}.pdf`;
    // link.click();
    handleClose();
  };

  const Icon = config.icon;
  const selectedCount = options.filter((opt) => opt.checked).length;

  return (
    <AriaDialogTrigger isOpen={isOpen} onOpenChange={onOpenChange}>
      <ModalOverlay isDismissable>
        <Modal>
          <Dialog>
            <div className="relative w-full overflow-hidden rounded-2xl bg-primary shadow-xl sm:max-w-lg">
              <CloseButton
                onClick={handleClose}
                theme="light"
                size="lg"
                className="absolute top-4 right-4 z-20"
              />

              {/* Header */}
              <div className="border-b border-secondary px-6 py-5">
                <div className="flex items-center gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-brand-100">
                    <Icon size={20} color="currentColor" className="text-brand-600" variant="Bold" />
                  </div>
                  <div>
                    <AriaHeading slot="title" className="text-lg font-semibold text-primary">
                      {config.title}
                    </AriaHeading>
                    <p className="text-sm text-tertiary">{itemName}</p>
                  </div>
                </div>
              </div>

              {/* Content */}
              <div className="max-h-[60vh] overflow-y-auto px-6 py-6">
                {!isComplete ? (
                  <>
                    <p className="text-sm text-secondary mb-4">
                      Select what to include in your PDF export:
                    </p>

                    <div className="flex flex-col gap-3">
                      {options.map((option) => (
                        <label
                          key={option.id}
                          className={cx(
                            "flex cursor-pointer items-start gap-3 rounded-lg border p-4 transition-all",
                            option.checked
                              ? "border-brand-200 bg-brand-50"
                              : "border-secondary bg-primary hover:bg-secondary_subtle"
                          )}
                        >
                          <Checkbox
                            isSelected={option.checked}
                            onChange={() => toggleOption(option.id)}
                          />
                          <div className="flex-1">
                            <p className="text-sm font-medium text-primary">{option.label}</p>
                            <p className="text-xs text-tertiary">{option.description}</p>
                          </div>
                        </label>
                      ))}
                    </div>
                  </>
                ) : (
                  <div className="flex flex-col items-center py-8">
                    <div className="flex h-16 w-16 items-center justify-center rounded-full bg-success-100">
                      <TickCircle size={32} color="currentColor" className="text-success-600" variant="Bold" />
                    </div>
                    <h3 className="mt-4 text-lg font-semibold text-primary">PDF Ready!</h3>
                    <p className="mt-1 text-sm text-tertiary text-center">
                      Your PDF has been generated and is ready to download.
                    </p>
                    <div className="mt-4 flex items-center gap-2 rounded-lg bg-secondary_subtle px-4 py-2">
                      <Document size={18} color="currentColor" className="text-tertiary" />
                      <span className="text-sm text-secondary">
                        {itemName.toLowerCase().replace(/\s+/g, "-")}.pdf
                      </span>
                    </div>
                  </div>
                )}

                {/* Exporting State */}
                {isExporting && (
                  <div className="absolute inset-0 flex flex-col items-center justify-center bg-primary/90">
                    <div className="h-12 w-12 animate-spin rounded-full border-4 border-brand-200 border-t-brand-600" />
                    <p className="mt-4 text-sm font-medium text-primary">Generating PDF...</p>
                    <p className="mt-1 text-xs text-tertiary">This may take a few moments</p>
                  </div>
                )}
              </div>

              {/* Footer */}
              <div className="flex items-center justify-between border-t border-secondary px-6 py-4">
                {!isComplete ? (
                  <>
                    <p className="text-xs text-tertiary">
                      {selectedCount} {selectedCount === 1 ? "section" : "sections"} selected
                    </p>
                    <div className="flex gap-3">
                      <Button size="md" color="secondary" onClick={handleClose}>
                        Cancel
                      </Button>
                      <Button
                        size="md"
                        iconLeading={({ className }) => <DocumentDownload size={18} color="currentColor" className={className} />}
                        onClick={handleExport}
                        isDisabled={selectedCount === 0 || isExporting}
                      >
                        Generate PDF
                      </Button>
                    </div>
                  </>
                ) : (
                  <>
                    <div />
                    <div className="flex gap-3">
                      <Button size="md" color="secondary" onClick={handleClose}>
                        Close
                      </Button>
                      <Button
                        size="md"
                        iconLeading={({ className }) => <DocumentDownload size={18} color="currentColor" className={className} />}
                        onClick={handleDownload}
                      >
                        Download PDF
                      </Button>
                    </div>
                  </>
                )}
              </div>
            </div>
          </Dialog>
        </Modal>
      </ModalOverlay>
    </AriaDialogTrigger>
  );
};

export default PdfExportModal;
