import type { WalkthroughStep } from "./types";

export const WALKTHROUGH_STEPS: WalkthroughStep[] = [
  {
    id: "welcome",
    stepNumber: 0,
    title: "Welcome to Protectron!",
    description: "Let's help you get started with EU AI Act compliance.",
    icon: "🎉",
    position: "center",
    actionType: "view",
    dynamicContent: true,
  },
  {
    id: "dashboard-overview",
    stepNumber: 1,
    title: "Dashboard",
    description: "This is your compliance command center. Here you'll see your overall compliance score, progress across all AI systems, pending actions and alerts, and quick access to important tasks. As you make progress, this dashboard will update in real-time.",
    icon: "📊",
    targetSelector: "[data-walkthrough='nav-dashboard']",
    targetPage: "/dashboard",
    position: "right",
    actionType: "view",
    highlights: [
      "Your overall compliance score",
      "Progress across all AI systems",
      "Pending actions and alerts",
      "Quick access to important tasks",
    ],
  },
  {
    id: "ai-systems-nav",
    stepNumber: 2,
    title: "AI Systems",
    description: "This is where you manage all your AI systems. For each AI system, you can view its risk classification, track compliance requirements, generate required documents, and upload evidence.",
    icon: "🤖",
    targetSelector: "[data-walkthrough='nav-ai-systems']",
    targetPage: "/dashboard",
    position: "right",
    actionType: "view",
    highlights: [
      "View risk classification",
      "Track compliance requirements",
      "Generate required documents",
      "Upload evidence",
    ],
    dynamicContent: true,
  },
  {
    id: "requirements-nav",
    stepNumber: 3,
    title: "Requirements",
    description: "Track every EU AI Act requirement for your AI systems. When you add an AI system, Protectron automatically generates a personalized checklist based on its risk classification.",
    icon: "✅",
    targetSelector: "[data-walkthrough='nav-requirements']",
    targetPage: "/dashboard",
    position: "right",
    actionType: "view",
    highlights: [
      "Article 9: Risk Management",
      "Article 10: Data Governance",
      "Article 11: Technical Documentation",
      "Article 12: Record-Keeping",
      "Article 13: Transparency",
      "Article 14: Human Oversight",
      "Article 15: Accuracy & Security",
    ],
  },
  {
    id: "documents-nav",
    stepNumber: 4,
    title: "Documents",
    description: "Generate AI-powered compliance documentation in minutes. Instead of spending weeks writing from scratch, use our AI to generate first drafts of Technical Documentation, Risk Assessment Reports, Data Governance Policies, Model Cards, and 15+ more document types.",
    icon: "📄",
    targetSelector: "[data-walkthrough='nav-documents']",
    targetPage: "/dashboard",
    position: "right",
    actionType: "view",
    tips: ["Answer guided questions → Review AI draft → Export as PDF/Word"],
  },
  {
    id: "evidence-nav",
    stepNumber: 5,
    title: "Evidence",
    description: "Upload and organize all your compliance evidence. Auditors will ask for proof. This is where you store documents, screenshots, test results, link evidence to specific requirements, track evidence freshness, and generate evidence reports.",
    icon: "🗃️",
    targetSelector: "[data-walkthrough='nav-evidence']",
    targetPage: "/dashboard",
    position: "right",
    actionType: "view",
    tips: ["Pro tip: Our SDK can automatically generate audit trail evidence from your AI system's production usage."],
  },
  {
    id: "reports-nav",
    stepNumber: 6,
    title: "Reports",
    description: "Generate audit-ready compliance reports with one click. When you need to prove compliance, generate Full Compliance Reports for regulators, Executive Summaries for leadership, Customer-Facing Reports for enterprise sales, and Gap Analysis Reports.",
    icon: "📈",
    targetSelector: "[data-walkthrough='nav-reports']",
    targetPage: "/dashboard",
    position: "right",
    actionType: "view",
  },
  {
    id: "create-ai-system",
    stepNumber: 7,
    title: "Create Your First AI System",
    description: "Now let's add your first AI system to start tracking compliance. Click the 'Add AI System' button to get started.",
    icon: "🚀",
    targetSelector: "[data-walkthrough='nav-ai-systems']",
    targetPage: "/ai-systems",
    position: "right",
    actionType: "view",
    dynamicContent: true,
  },
  {
    id: "ai-system-detail",
    stepNumber: 8,
    title: "AI System Created!",
    description: "This is your AI system's compliance headquarters. Notice the tabs at the top: Overview shows risk classification and compliance status, Requirements shows all EU AI Act requirements, Documents shows generated compliance documents, and Evidence shows uploaded proof.",
    icon: "🎉",
    targetSelector: "[data-walkthrough='nav-ai-systems']",
    targetPage: "/ai-systems",
    position: "right",
    actionType: "view",
    highlights: [
      "Overview — Risk classification and compliance status",
      "Requirements — All EU AI Act requirements for this system",
      "Documents — Generated compliance documents",
      "Evidence — Uploaded proof of compliance",
    ],
  },
  {
    id: "requirements-tab",
    stepNumber: 9,
    title: "Your Requirements Checklist",
    description: "Protectron automatically generated requirements for this AI system, organized by EU AI Act article. For each requirement, you can mark as Complete with evidence, mark as In Progress, generate related documents, and upload supporting evidence.",
    icon: "✅",
    targetSelector: "[data-walkthrough='nav-requirements']",
    targetPage: "/ai-systems",
    position: "right",
    actionType: "view",
    dynamicContent: true,
  },
  {
    id: "completion",
    stepNumber: 10,
    title: "You're All Set!",
    description: "You've completed the Protectron walkthrough. You're now ready to start your compliance journey!",
    icon: "🎉",
    position: "center",
    actionType: "view",
    dynamicContent: true,
  },
];

export const TOTAL_WALKTHROUGH_STEPS = WALKTHROUGH_STEPS.length;

export const getStepById = (id: string): WalkthroughStep | undefined => {
  return WALKTHROUGH_STEPS.find((step) => step.id === id);
};

export const getStepByNumber = (stepNumber: number): WalkthroughStep | undefined => {
  return WALKTHROUGH_STEPS.find((step) => step.stepNumber === stepNumber);
};
